// <auto-generated />
namespace HPSMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class VIEWER : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VIEWER));
        
        string IMigrationMetadata.Id
        {
            get { return "201603140030247_VIEWER"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
